### PR TITLE
Add SPM Support

### PR DESCRIPTION
**Pull request by joshuapoq**
- Added `Package.swift` using binary target wrapping xcframework.
- Updated the LearningApp to use the Swift Package.
- Updated the readme.

### CODE REVIEW

**Comment by joshuapoq** [comment]
Hey guys, please can we get this support. @skytan4

**Comment by joshuapoq** [comment]
Looks like I missed the `bundle`. Will investigate if there's a way to package it as part of the SPM product.

**Comment by skytan4** [comment]
Thank you @joshuapoq. Requests for new features are gathered through Voice of Customer Requests.  Please make this request through your Salesforce Account Manager.

**Comment by gotev** [comment]
SPM is a much needed feature, please merge this 😉

**Comment by joshuapoq** [comment]
Whilst I completely agree and it's ridiculous to request a now common basic requirement for a framework - unfortunately, this is missing the resources `bundle` @gotev so leads to runtime crashes. It needs a bit more work as that bundle should either be built into the `xcframework` or distributed in its own target as part of the `Package.swift` but I've no time to figure that out.

I think I'll close this PR for now but this should have already been done and released by your team @skytan4.

**Comment by sfmc-mobilepushsdk** [comment]
Thank you @joshuapoq.

**Comment by alexookah** [comment]
So still no SPM support on latest release :(

**Comment by eyehuda-sf** [comment]
SPM is supported in v8.x releases. It seems like the ask here is to support SPM on v7.x (the master branch is correlated to v7.x, and the [spm branch](https://github.com/salesforce-marketingcloud/MarketingCloudSDK-iOS/tree/spm) is for the 8.x versions). 

In that case, please open a Voice of Customer Requests through your Salesforce Account Manager. Thanks!

**Comment by alexookah** [comment]
It's a bit confusing. the v7.x should be in a seperate branch and the latest should be in the master branch. I was looking for the v8 SPM

**Pull request closed without merging**
