### PR TITLE
fix: MarketingCloudSDK bundle inclusion in app

### PR DESCRIPTION
**Pull request by luquanlang**
**Context**
With the latest version of the swift package, we had to manually pull in the `MarketingCloudSDK-iOS.bundle` to the _Copy Bundle Resources_ in the app when adding the package, as indicated in the documentation.

> Manually pull in the Resources/MarketingCloudSDK.bundle from the sources folder in the Mobile Push SPM and link it with the binary in build phase.
https://salesforce-marketingcloud.github.io/MarketingCloudSDK-iOS/get-started/get-started-migration.html

Otherwise, the app crashed after launching. Furthermore, we had to pay attention and copy again the `.bundle` if the package was updated, as mentioned in the troubleshoot section of the doc:

> When the SDK is upgraded to latest version, there might be changes to the resources bundle (MarketingCloudSDK.bundle) that comes packaged with the SDK. If the right versions are not copied, the app crashes with the exception as the SDK might not find the required resources in the .bundle file.

**The suspected problem**

I observed that the `Package.swift` file had the following structure:

root
  |-- Sources
        |-- MarketingCloudSDKResources
               |-- Resources
               
 But the target declaration was:
```
.target(
     name: "MarketingCloudSDKResources",
     resources: [.process("Resources")]
 )
```

Which didn't match the directories structure.

**Solution** 

Moving _MarketingCloudSDKResources_ directory under the root level so that the target definition matches, resulting in the following file structure:

root
   |-- MarketingCloudSDKResources
          |-- Resources
          
          
 Tested locally and worked without adding the `.bundle` manually on XCode 14.2

### CODE REVIEW

**Comment by eyehuda-sf** [comment]
@luquanlang Thank you for your contribution. We're reviewing this internally with the team.

**Comment by eyehuda-sf** [comment]
@luquanlang Thank you for your contribution. We're reviewing this internally with the team.

**Comment by luquanlang** [comment]
I tested it again and I'm afraid this is not fixing the issue 😓 
Maybe the cache or Derived Data played a trick on me when I checked it yesterday. Sorry for any inconvenience

**Comment by billmote** [comment]
> I tested it again and I'm afraid this is not fixing the issue 😓 Maybe the cache or Derived Data played a trick on me when I checked it yesterday. Sorry for any inconvenience

No inconvenience at all. @eyehuda-sf and company have been working to simplify this. Hopefully your submission provided them some insights. Thank you!

**Comment by luquanlang** [comment]
@billmote BTW, do you have a timeframe for this?

**Comment by billmote** [comment]
Sorry, we can't make timeline or roadmap commitments in a public forum. Your account executive could reach out internally for any official timeline, but do know that the work is prioritized and actively in development.

**Pull request closed without merging**
